name: Check ESLint

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  testing:
    name: Check ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint
        run: npm run eslint